In [41]:
import torch
import numpy as np
import pandas as pd
import random

In [42]:
t = np.array([[0.8, 0.2, 0], 
              [0, 0.6, 0.4], 
              [0.05, 0, 0.95]])
print(t)

[[0.8  0.2  0.  ]
 [0.   0.6  0.4 ]
 [0.05 0.   0.95]]


In [43]:
t_2 = t @ t

print(t_2)

[[0.64   0.28   0.08  ]
 [0.02   0.36   0.62  ]
 [0.0875 0.01   0.9025]]


In [44]:
t_3 = t_2 @ t

print(t_3)

[[0.516    0.296    0.188   ]
 [0.047    0.22     0.733   ]
 [0.115125 0.0235   0.861375]]


In [45]:
t_5 = t_3 @ t_2

print(t_5)

[[0.35261    0.25292    0.39447   ]
 [0.0986175  0.09969    0.8016925 ]
 [0.14952031 0.04930875 0.80117094]]


In [46]:
t_50 = np.linalg.matrix_power(t, 50)

# Assuming t_50 is already defined as a NumPy array
for row in t_50:
    print(" ".join(f"{elem:.4f}" for elem in row))

0.1818 0.0909 0.7273
0.1818 0.0909 0.7273
0.1818 0.0909 0.7273
